export const TOAST_MSG = {
  SUCCESS: 'success',
  ERROR: 'error',
  NO_INTERNET: 'There is an issue with the network connection.',
  SERVER_ERROR: 'Internal Server Error.',
  FIELD_ERROR: 'Please Enter Valid Email and Password',
  INVALID_CREDENTIAL: 'Invalid Credentials',
  LOGOUT_SUCCESS: 'Logout Successfully',
  NO_DATA: 'No Data Available',
  REQUEST_FAIL: 'Request Failed',
  DATA_LOADED: 'Meetings Loaded.',
  MEETING_ACCEPTED_SUCCESSFULLY: 'Meeting has been accepted successfully',
  MEETING_REJECTED_SUCCESSFULLY: 'Meeting has been rejected successfully',
  MEETING_ACCEPT_FAILED: 'Meeting accept failed',
  MEETING_REJECT_FAILED: 'Meeting reject failed',
  VALID_CONTENT: 'Please enter valid content',
  NO_EVENTS_DATA: 'Events not available',
  NO_EVENTS_DATA_PAGINATION: 'No more events available',
  ONE_2_ONE_MEETING_REQUEST_SUCCESS:
    'One to one meeting request sent successfully',
  NO_DATA_PAGINATION: (type: string) =>
    `No more ${type.toLowerCase()} available`,
  NO_CHAPTER_REPORT: 'No chapter report found',
  REFERENCE_SEND_SUCCESSFULLY: 'Reference send successfully',
  REFERENCE_SEND_FAILED: 'Reference send failed',
  REFERENCE_DELETED_SUCCESSFULLY: 'Reference deleted successfully',
  REFERENCE_EDITED_SUCCESSFULLY: 'Reference edited successfully',
  DEAL_DECLARE_SUCCESSFULLY: 'Deal declare successfully',
  DEAL_DELETED_SUCCESSFULLY: 'Deal deleted successfully',
  DEAL_EDITED_SUCCESSFULLY: 'Deal edited successfully',
};
